channels:
  - ioam/label/dev
  - conda-forge
  - defaults

dependencies:
  - ioam/label/dev::holoviews
  - appmode
  - datashader
  - geoviews
  - gridgeo
  - jupyter
  - notebook
  - matplotlib
  - notebook
  - pandas
